# 使用官方的Node.js作为父镜像  
FROM node:lts-alpine as build-stage  
WORKDIR /app  

# 复制package*.json  
COPY package*.json ./  

# 安装项目依赖  
RUN npm install  

# 复制项目源文件  
COPY . .  

# 构建生产环境应用  
RUN npm run build  

# 使用Nginx作为静态文件服务器  
FROM nginx:stable-alpine as production-stage  
COPY --from=build-stage /app/dist /usr/share/nginx/html  

# 前台运行Nginx  
CMD ["nginx", "-g", "daemon off;"]